var h,aa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},ba=function(a,b){function c(){}c.prototype=b.prototype;a.Vb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Sb=function(a,c,g){for(var e=Array(arguments.length-2),d=2;d<arguments.length;d++)e[d-2]=arguments[d];return b.prototype[c].apply(a,e)}};var k={Rb:{}},n={},p,ca=!1,q=function(a){try{ca&&window.console&&window.console.log&&window.console.log(a)}catch(b){}},r=function(a,b){if(!a)return-1;if(a.indexOf)return a.indexOf(b,void 0);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1},t=function(a,b){function c(){}if(!a)throw"Child class cannot be empty.";if(!b)throw"Parent class cannot be empty.";c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a},da=function(a){return"[object Function]"===Object.prototype.toString.call(a)},
ea=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];if(null===d||void 0===d)d="";b.push(encodeURIComponent(c)+"="+encodeURIComponent(d))}return b.join("&")},fa=function(a){a=(new RegExp("[&#]"+a+"=([^&]*)")).exec(window.location.hash);return null==a?"":decodeURIComponent(a[1].replace(/\+/g," "))},ga=function(a,b,c){if(a.addEventListener)a.addEventListener(b,c,!1);else if(a.attachEvent)a.attachEvent("on"+b,c);else throw"Add event handler for "+b+" failed.";},ha=function(a,b){a=
(a||"").split(" ");b=(b||"").split(" ");for(var c=0;c<b.length;c++)if(b[c]&&0>r(a,b[c]))return!1;return!0},ia=function(){if("undefined"!=typeof p)return p;var a;a=window.localStorage?window.localStorage:void 0;if(!a)return p=!1;try{a.setItem("test","test"),a.removeItem("test"),p=!0}catch(b){p=!1}return p},ja=function(){var a=navigator.userAgent.toLowerCase();return-1!=a.indexOf("msie")&&8==parseInt(a.split("msie")[1],10)},u=function(){return Object.hasOwnProperty.call(window,"ActiveXObject")&&!window.ActiveXObject},
ka=function(){var a=navigator.userAgent;return!!a&&/Edge\/\d+/.test(a)},la=function(){var a=navigator.userAgent,b;if(b=!!a&&-1!=a.indexOf("CriOS"))b=-1,(a=a.match(/CriOS\/(\d+)/))&&a[1]&&(b=parseInt(a[1],10)||-1),b=48>b;return b},ma=function(){var a=navigator.userAgent.toLowerCase();return-1<a.indexOf("safari/")&&0>a.indexOf("chrome/")&&0>a.indexOf("crios/")&&0>a.indexOf("android")},w=function(a){this.ya=a||[];this.B={}};
w.prototype.addEventListener=function(a,b){if(!(0<=r(this.ya,a)))throw"Unrecognized event type: "+a;if(!da(b))throw"The listener for event '"+a+"' is not a function.";this.B[a]||(this.B[a]=[]);0>r(this.B[a],b)&&this.B[a].push(b)};w.prototype.removeEventListener=function(a,b){if(!(0<=r(this.ya,a)))throw"Unrecognized event type: "+a;da(b)&&this.B[a]&&this.B[a].length&&(b=r(this.B[a],b),0<=b&&this.B[a].splice(b,1))};
w.prototype.dispatchEvent=function(a){var b=a.type;if(!(b&&0<=r(this.ya,b)))throw"Failed to dispatch unrecognized event type: "+b;if(this.B[b]&&this.B[b].length)for(var c=0,d=this.B[b].length;c<d;c++)this.B[b][c](a)};n=n||{};n.H=function(a){a=encodeURIComponent(a);var b=n.Ka();if(b&&(a=b.match("(^|;) ?"+a+"=([^;]*)(;|$)"))&&2<a.length&&(a=a[2]))return decodeURIComponent(a)};n.lb=function(a){var b;(a=n.H(a))&&(b=String(na(a)));return b};n.Ka=function(){return document.cookie};
n.Lb=function(a){document.cookie=a};k=k||{};
k.tb=function(a,b){if(!0===k.oa)a();else{var c=2,d=function(){c--;0==c&&(k.oa=!0,a())},e=function(a){b(a)};switch(oa()){case "sessionStorage":k.ca=new x;k.ca.F(d,e);break;case "inMemoryStorage":k.ca=new y;k.ca.F(d,e);break;default:d=Error("Unsupported storage type: "+oa());b(d);return}switch(pa()){case "localStorage":k.N=new z;k.N.F(d,e);break;case "indexedDb":k.N=new A;k.N.F(d,e);break;case "cookieStorage":k.N=new B;k.N.F(d,e);break;default:d=Error("Unsupported storage type: "+pa()),b(d)}}};
k.Ma=function(){if(!k.oa)throw Error("Storages are not initialized yet!");return k.N};k.rb=function(){if(!k.oa)throw Error("Storages are not initialized yet!");return k.ca};var z=function(){};z.prototype.F=function(a,b){ia()?(this.$=window.localStorage,a()):b&&b(Error("localStorage is not available in the current environment."))};z.prototype.getItem=function(a,b){b(this.$.getItem(a))};z.prototype.setItem=function(a,b,c){void 0===b||null===b?this.$.removeItem(a):this.$.setItem(a,b);c&&c()};
z.prototype.removeItem=function(a,b){this.$.removeItem(a);b&&b()};var A=function(){};A.prototype.F=function(a,b){var c=this,d=window.indexedDB.open("oauth");d.onsuccess=function(b){c.ja=b.target.result;a()};d.onupgradeneeded=function(a){a.target.result.createObjectStore("oauth")};d.onerror=function(a){a=a.target.errorCode;b&&b(Error("IndexedDb initialization failed: "+a))}};A.prototype.getItem=function(a,b){var c=this.ja.transaction("oauth","readwrite").objectStore("oauth").get(a);c.onsuccess=function(){b(c.result)}};
A.prototype.setItem=function(a,b,c){var d=this.ja.transaction("oauth","readwrite").objectStore("oauth");if(void 0===b||null===b)d["delete"](a);else d.put(b,a);d.transaction.oncomplete=function(){c&&c()}};A.prototype.removeItem=function(a,b){var c=this.ja.transaction("oauth","readwrite").objectStore("oauth");c["delete"](a);c.transaction.oncomplete=function(){b&&b()}};var y=function(){};y.prototype.F=function(a){this.va={};a()};y.prototype.getItem=function(a,b){b(this.va[a]||null)};
y.prototype.setItem=function(a,b,c){this.va[a]=b;c&&c()};y.prototype.removeItem=function(a,b){delete this.va[a];b&&b()};var x=function(){};x.prototype.F=function(a,b){ia()?(this.ba=window.sessionStorage,a()):b&&b(Error("sessionStorage is not available in the current environment."))};x.prototype.getItem=function(a,b){b(this.ba.getItem(a))};x.prototype.setItem=function(a,b,c){void 0===b||null===b?this.ba.removeItem(a):this.ba.setItem(a,b);c&&c()};
x.prototype.removeItem=function(a,b){this.ba.removeItem(a);b&&b()};var B=function(){this.yb=C.Wa};B.prototype.F=function(a,b){navigator.cookieEnabled?a():b&&b(Error("Cookies are not enabled in current environment."))};B.prototype.getItem=function(a,b){for(var c=null,d=qa(a),e=0;e<d.length;e++)if(d[e].key==a){c=d[e].value;break}b(c)};
B.prototype.setItem=function(a,b,c){var d=C.la(a.split(C.i)[0]);if(d){var e=ra(d);b={key:a,value:b};for(var g=0;g<e.length;g++)if(e[g].key==a){e.splice(g,1);break}e.push(b);sa(this,d,e)}c&&c()};B.prototype.removeItem=function(a,b){for(var c=qa(a),d=0;d<c.length;d++)if(c[d].key==a){c.splice(d,1);break}(a=C.la(a.split(C.i)[0]))&&sa(this,a,c);b&&b()};
var qa=function(a){return(a=C.la(a.split(C.i)[0]))?ra(a):[]},ra=function(a){a=n.H(a);return k.eb(a||null)},sa=function(a,b,c){var d=k.gb(c);d.length>a.yb?(c.splice(0,1),0<c.length?sa(a,b,c):q("Failed to write Cookie based cache due to the big size.")):k.Ta(b,d)};k.cb=function(a){try{return atob(a)}catch(b){return a}};k.fb=function(a){try{return btoa(a)}catch(b){return a}};
k.eb=function(a){if(!a)return[];a=k.cb(a);try{return JSON.parse(a).items||[]}catch(b){return q("Error while parsing items from cookie:"+b.message),[]}};k.gb=function(a){return k.fb(JSON.stringify({items:a}))};k.Ta=function(a,b){var c=window.location.pathname;a=encodeURIComponent(a)+"="+encodeURIComponent(b)+"; domain="+window.location.hostname+";";-1!=navigator.userAgent.toLowerCase().indexOf("msie")||u()||(a+=" path="+c+";");"https:"==window.location.protocol&&(a+=" secure;");n.Lb(a)};
k.Ub=function(a){var b=n.Ka();if(b)for(var b=b.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,"").split(/\s*(?:\=[^;]*)?;\s*/),c=0;c<b.length;c++){var d=decodeURIComponent(b[c]);0==d.indexOf(a)&&k.Ta(d,"")}};var D=function(a){this.Pa=a;w.call(this,["storageValueChanged"])};t(D,w);var ta=function(a,b){k.Ma().getItem(a.Pa,b)};D.prototype.addListener=function(a){this.addEventListener("storageValueChanged",a)};
D.prototype.start=function(){var a=this;ta(this,function(b){a.Cb=b;a.Qa=0;a.pa=window.setInterval(ua(a),200)})};D.prototype.stop=function(){void 0!==this.pa&&(clearInterval(this.pa),this.pa=void 0)};
var ua=function(a){return function(){a.Qa++;ta(a,function(b){b!=a.Cb?(a.dispatchEvent({type:"storageValueChanged",key:a.Pa,newValue:b}),a.stop()):1500<=a.Qa&&a.stop()})}},na=function(a){var b=0,c,d,e;if(a)for(c=0,e=a.length;c<e;c++)d=a.charCodeAt(c),b=(b<<5)-b+d,b|=0;return b},E=function(a){return!!a&&0<=a.indexOf(C.i)},va=function(a,b){if(!a&&!b)return!0;if(!a||!b)return!1;a=a.extraQueryParams;b=b.extraQueryParams;if(!a&&!b)return!0;if(!a||!b||Object.keys&&Object.keys(a).length!=Object.keys(b).length)return!1;
for(var c in a)if(a[c]!==b[c])return!1;if(!Object.keys)for(c in b)if(a[c]!==b[c])return!1;return!0},C=C||{};C.ha="SID";C.Fa="SSID";C.Va=100;C.Ha="/oauth2/sessionstate/action/updateState";C.za="/oauth2/sessionstate/action/checkOrigin";C.Ea="/oauth2/permission/action/refresh";C.Da="/oauth2/permission/action/code";C.ga="/oauth2/permission/action/listSessions";C.Za="/o/oauth2/revoke";C.i="::";C.fa="_ss_";C.Ca="_tr_";C.T="oauth2_ss";C.Aa="oauth2_cs";C.Ga="oauth2_tr";C.Xa="oauth2_is";C.S="oauth2_ar";
C.Ba="oauth2c_";C.Wa=1500;C.Qb=function(){var a={fa:1,Ca:2,T:3,Aa:4,Ga:5,S:6},b;for(b in a)if(a=C[b],!a||0<=a.indexOf(C.i))throw"Invalid value for 'oauth2.spi."+b+"'.";};C.Qb();C.Ya=512;C.$a=function(a){var b;(b=void 0===a.hint)||(b=a.hint,b=(""===b?!0:b?"string"==typeof b||"object"==typeof b&&b.constructor===String:!1)&&a.hint.length<=C.Ya);return!a.id&&b};C.pb=function(){return"https:"==window.location.protocol?C.Fa:C.ha};
C.la=function(a){switch(a){case C.S:return C.Ba+C.S;case C.T:return C.Ba+C.T;default:return null}};var pa=function(){return ma()&&!ia()||u()&&!window.indexedDB?"cookieStorage":u()||ka()?"indexedDb":"localStorage"},oa=function(){return ma()&&!ia()?"inMemoryStorage":"sessionStorage"},n=n||{};n.ea="cookieValueChanged";var wa=function(a,b){this.Ja=a;this.ub=b;w.call(this,[n.ea])};t(wa,w);wa.prototype.H=function(){return n.H(this.Ja)};var F=function(a){return n.lb(a.Ja)};
wa.prototype.addListener=function(a){this.addEventListener(n.ea,a)};
var za=function(a){xa(a);a.aa=a.H();a.wa=window.setInterval(ya(a),a.ub);q("IDP Session Cookie monitor is started.")},xa=function(a){void 0!==a.wa&&(window.clearInterval(a.wa),a.wa=void 0,q("IDP Session Cookie monitor is stoped."))},ya=function(a){return function(){var b=a.H();if(a.aa!=b){var c={type:n.ea,newHash:b&&na(b),oldHash:a.aa&&na(a.aa)};a.aa=b;a.dispatchEvent(c)}}},Aa=function(a,b){this.b=a;this.Ua=b},Ba=function(a,b,c){var d=C.Za,e=new XMLHttpRequest;e.onreadystatechange=function(){if(4==
e.readyState&&200==e.status){var a;e.responseText&&(a=window.JSON.parse(e.responseText));c(a)}};e.open("POST",d,!0);e.setRequestHeader("Content-type","application/x-www-form-urlencoded");var g="xsrfToken=";a.Ua&&(g+=a.Ua);if(b)for(var f in b)f&&b[f]&&(g+="&"+f+"="+encodeURIComponent(b[f]));q("Call "+d+" with postData: "+g);e.send(g)},G=function(a,b,c,d,e){var g=new XMLHttpRequest;g.onreadystatechange=function(){if(4==g.readyState&&200==g.status){var a;g.responseText&&(a=window.JSON.parse(g.responseText));
d(a)}};if(b=ea(b))a+=0>a.indexOf("?")?"?":"&",a+=b;g.open("GET",a,!0);e&&(g.withCredentials=!0);if(c)for(var f in c)if(c.hasOwnProperty(f)){e=c[f];if(null===e||void 0===e)e="";g.setRequestHeader(f,e)}q("Call "+a+" with Get method.");g.send()},Ca=function(a,b,c){G(C.za,{origin:a.b,client_id:b},null,c,!1)},Da=function(a,b,c){b&&b.length?G(C.Ha,{login_hint:b.join(" "),origin:a.b},null,c,!1):c({activeHints:{}})},Ea=function(a,b,c){b.origin=a.b;delete b.redirect_uri;delete b.app_package_name;G(C.Ea,b,
null,c,!1)},Fa=function(a,b,c){b.origin=a.b;delete b.redirect_uri;delete b.app_package_name;delete b.response_type;G(C.Da,b,null,c,!1)},Ga=function(a,b,c){b.origin=a.b;delete b.redirect_uri;delete b.response_type;delete b.app_package_name;delete b.login_hint;G(C.ga,b,null,c,!1)},Ha=function(a,b,c){Ba(a,{token:b},c)},k=k||{},Ia=function(){};Ia.prototype.w=function(){return!1};var Ja={};
k.Eb=function(){var a=new H;if(!a)throw"policy cannot be empty.";if(k.Na("DEFAULT"))throw"Duplicate policyName [DEFAULT].";Ja.DEFAULT=a};k.Na=function(a){for(var b in Ja)if(a==b)return!0;return!1};k.La=function(a){return a&&k.Na(a)?a:"DEFAULT"};k.mb=function(a){return Ja[k.La(a)]};k.w=function(a,b,c,d){return k.mb(d).w(a,b,c)};k.Tb=function(a,b,c,d){if(!k.w(a,b,c,d))throw"permission_error";};var Ka=function(){};t(Ka,Ia);Ka.prototype.w=function(a,b,c){a=c?this.ma(a):this.na(a);return 0<=r(a,b)};
Ka.prototype.na=function(a){var b=[];if(a&&(b.push(a),"http://"==a.substring(0,7)||"https://"==a.substring(0,8))){var c=document.createElement("a");c.href=a;a!=c.protocol+"//"+c.hostname&&b.push(c.protocol+"//"+c.hostname);"https:"==c.protocol&&b.push("http://"+c.hostname)}return b};
Ka.prototype.ma=function(a){var b=[];if(a){b.push(a);var c=document.createElement("a");c.href=a;if("http:"==c.protocol||"https:"==c.protocol)for(a=c.hostname.split(".");1<a.length;)b.push(c.protocol+"//"+a.join(".")),"https:"==c.protocol&&b.push("http://"+a.join(".")),a.shift()}return b};var H=function(){};t(H,Ia);H.prototype.w=function(a,b,c){a=c?this.ma(a):this.na(a);return 0<=r(a,b)};
H.prototype.na=function(a){var b=[];if(a&&(b.push(a),"https://"==a.substring(0,8))){var c=document.createElement("a");c.href=a;""!=c.port&&0!=c.port&&443!=c.port||b.push("http://"+c.hostname)}return b};
H.prototype.ma=function(a){var b=[];if(a){var c=document.createElement("a");c.href=a;if("https:"==c.protocol&&(""==c.port||0==c.port||443==c.port)||"http:"==c.protocol&&(""==c.port||0==c.port||80==c.port))for(a=c.hostname.split(".");1<a.length;)b.push(c.protocol+"//"+a.join(".")),"https:"==c.protocol&&b.push("http://"+a.join(".")),a.shift();else b.push(a)}return b};k.Eb();var I=function(){};I.prototype.ra=function(){return!0};var J=function(a){return a.ra()?k.rb():k.Ma()};
I.prototype.h=function(){throw Error("unimplemented abstract method");};I.prototype.G=function(){throw Error("unimplemented abstract method");};I.prototype.l=function(){throw Error("unimplemented abstract method");};I.prototype.j=function(){throw Error("unimplemented abstract method");};var K=function(){};t(K,I);
K.prototype.l=function(a,b,c){var d=this,e=this.h(a);J(this).getItem(e,function(a){var f;if(a)try{var g=window.JSON.parse(a);if(g.cookieHash!=b){J(d).removeItem(e,function(){c(void 0)});return}f=g&&g.cachedValue}catch(m){}c(f)})};K.prototype.j=function(a,b,c,d){a=this.h(a);void 0===b||null===b?J(this).removeItem(a,d):(b=JSON.stringify({cookieHash:c,cachedValue:b}),J(this).setItem(a,b,d))};var L=function(){};t(L,I);
L.prototype.l=function(a,b,c){J(this).getItem(this.h(a),function(a){var b;if(a)try{var d=window.JSON.parse(a);b=d&&d.cachedValue}catch(f){}c(b)})};L.prototype.j=function(a,b,c,d){a=this.h(a);void 0===b||null===b?J(this).removeItem(a,d):(b=JSON.stringify({cachedValue:b}),J(this).setItem(a,b,d))};var M=function(){};t(M,L);M.prototype.ra=function(){return!1};M.prototype.h=function(a){return[C.S,a.origin,a.a,a.id].join(C.i)};
M.prototype.G=function(a){var b={};a&&(a=a.split(C.i),4==a.length&&(b.origin=a[1],b.a=a[2],b.id=a[3]));return b};var La=function(){};t(La,K);La.prototype.h=function(a){return[C.Aa,a.origin,a.a].join(C.i)};La.prototype.G=function(a){a=a.split(C.i);var b={};3==a.length&&(b.origin=a[1],b.a=a[2]);return b};var N=function(){};t(N,K);N.prototype.h=function(a){return[C.Xa,a.origin,a.a].join(C.i)};
N.prototype.l=function(a,b,c){var d=this;K.prototype.l.call(this,a,b,function(b){b&&b.expires_at?6E4>b.expires_at-(new Date).getTime()?J(d).removeItem(d.h(a),c):ha(b.scope,a.scope)&&ha(a.scope,b.scope)?(b.expires_in=Math.floor((b.expires_at-(new Date).getTime())/1E3),c&&c(b)):J(d).removeItem(d.h(a),c):c&&c(void 0)})};N.prototype.j=function(a,b,c,d){var e;b&&b.expires_at&&18E4<b.expires_at-(new Date).getTime()&&(e=b);K.prototype.j.call(this,a,e,c,d)};var O=function(){};t(O,L);O.prototype.ra=function(){return!1};
O.prototype.h=function(a){return[C.T,a.domain,a.V?"1":"0",k.La(a.I),a.id||C.fa].join(C.i)};O.prototype.G=function(a){a=a.split(C.i);var b={};5==a.length&&(b.domain=a[1],b.V="1"==a[2],b.I=a[3],b.id=a[4]);"DEFAULT"==b.I&&delete b.I;b.id==C.fa&&delete b.id;return b};var P=function(a){this.Bb=a||C.Ga};t(P,K);P.prototype.h=function(a){return[this.Bb,a.origin,a.a,a.id||C.Ca].join(C.i)};
P.prototype.l=function(a,b,c){var d=this;K.prototype.l.call(this,a,b,function(b){b&&b.P&&b.P.expires_at?a.xb!=b.P.login_hint?J(d).removeItem(d.h(a),c):6E4>b.P.expires_at-(new Date).getTime()?J(d).removeItem(d.h(a),c):ha(b.P.scope,a.scope)?ha(b.responseType,a.responseType)?(b=b.P,b.expires_in=Math.floor((b.expires_at-(new Date).getTime())/1E3),c&&c(b)):J(d).removeItem(d.h(a),c):J(d).removeItem(d.h(a),c):c&&c(void 0)})};
P.prototype.j=function(a,b,c,d){var e;b&&b.expires_at&&18E4<b.expires_at-(new Date).getTime()&&(e={P:b,responseType:a.responseType});K.prototype.j.call(this,a,e,c,d)};var Ma=function(a,b){this.b=a;this.ta=b;this.Y={};this.X={}},Na=function(a,b){if(!b)throw"message object cannot be null.";b.rpcToken=a.ta;b=JSON.stringify(b);q("IDP IFrame sends message: "+b);window.parent.postMessage(b,a.b)},Q=function(a,b,c){b&&Na(a,{id:b,result:c})};
Ma.prototype.Db=function(a){if(a.source==window.parent&&a.origin==this.b){q("IDP Session State IFrame receive message:"+a.data);try{var b=window.JSON.parse(a.data)}catch(c){return}(b.rpcToken||this.ta)&&b.rpcToken!=this.ta?q("RPC token mismatch."):b&&b.method&&this.Y[b.method]?(a=this.Y[b.method],a.rpcIdRequired&&!b.id?q("Bad request."):a.validator&&!a.validator(b)?(q("Bad request."),Na(this,{id:b.id,error:"bad_request"})):a.handler(b)):q("Bad request.")}};
var R=function(a,b){if(b&&b.type&&a.X[b.type]){var c=a.X[b.type].filter;c&&!c(b)||Na(a,{method:"fireIdpEvent",params:b})}else q("Invalid event type.")},Oa=function(a,b){a.Y={};a.X={};if(b){if(b.rpcs)for(var c=0;c<b.rpcs.length;c++){var d=b.rpcs[c];if(!d.method||!d.handler)throw"Error in RPC policy: method or handler is empty.";if(a.Y[d.method])throw"Error in RPC policy: duplicate entry for RPC '"+d.method+"'.";a.Y[d.method]={handler:d.handler,rpcIdRequired:d.rpcIdRequired,validator:d.validator}}if(b.events)for(c=
0;c<b.events.length;c++){d=b.events[c];if(!d.type)throw"Error in Event policy: type is empty.";if(a.X[d.type])throw"Error in Event policy: duplicate entry for type '"+d.type+"'.";a.X[d.type]={filter:d.filter}}}},Pa=function(a,b,c,d){R(a,{type:"sessionStateChanged",clientId:b,user:c,sessionState:d})},Qa=function(a){var b=new O,c=C.T+C.i;return function(d){if(d.key&&0===d.key.indexOf(c)){var e=b.G(d.key);if(k.w(a.b,e.domain,e.V,e.I)){var g;if(d.newValue)try{var f=JSON.parse(d.newValue);f&&(g=f.cachedValue)}catch(l){return}R(a,
{type:"sessionSelectorChanged",newValue:g,crossSubDomains:e.V,domain:e.domain,policy:e.I,id:e.id})}}}},Ra=function(a){var b=new M,c=[C.S,a.b].join(C.i)+C.i;return function(d){if(!d.key&&ja()){var e,g=null,f=[];for(d=0;d<window.localStorage.length;d++){var l=window.localStorage.key(d);if(0===l.indexOf(c))if(g)f.push(l);else{var m=window.localStorage.getItem(l);f.push(l);if(m){try{e=window.JSON.parse(m)}catch(v){continue}e&&e.cachedValue&&(g=b.G(l),g={type:"authResult",clientId:g.a,id:g.id,authResult:e.cachedValue})}}}for(d=
0;d<f.length;d++)window.localStorage.removeItem(f[d]);(e=g)&&R(a,e)}else if(d.key&&0===d.key.indexOf(c)&&d.newValue){try{f=window.JSON.parse(d.newValue)}catch(v){return}f&&f.cachedValue&&(e=b.G(d.key),e={type:"authResult",clientId:e.a,id:e.id,authResult:f.cachedValue},R(a,e))}}},Sa=function(a,b){this.b=a;this.u=b;this.Ia=new La;this.Ra=new O;this.xa=new P;this.M=new N},Ta=function(a,b,c,d,e){a.Ia.j({origin:a.b,a:b},{user:c.C,session:c.C?c.J:void 0},d,e)},Ua=function(a,b,c){a.Ia.l({origin:a.b,a:b},
F(a.u),c)},Va=function(a,b,c,d,e,g,f){a.xa.l({xb:b,origin:a.b,a:c,responseType:d,scope:e,id:g},F(a.u),f)},Wa=function(a,b,c,d,e,g,f){a.xa.j({origin:a.b,a:c,responseType:d,id:g},e,b,f)},Xa=function(a,b,c){var d=a.xa;a={origin:a.b,a:b};J(d).removeItem(d.h(a),c)},Ya=function(a,b,c,d,e,g){if(!a.w(b,c,e))throw"Permission denied for '"+a.b+"' to read session selector for domain '"+b+"'.";a.Ra.l({domain:b,V:c,I:e,id:d},void 0,function(a){g&&g(a)})},Za=function(a,b,c,d,e,g,f){if(!a.w(b,c,g))throw"Permission denied for '"+
a.b+"' to write session selector for domain '"+b+"'.";a.Ra.j({domain:b,V:c,I:g,id:e},d,void 0,f)};Sa.prototype.w=function(a,b,c){return k.w(this.b,a,b,c)};
var $a=function(a,b,c,d){a.M.l({origin:a.b,a:b,scope:c},F(a.u),d)},ab=function(a,b,c,d,e){a.M.j({origin:a.b,a:c},d,b,e)},bb=function(a,b,c){this.L=a;this.c=b;this.g=c},cb=function(a,b,c){a.C?c&&void 0!==c[a.C]?(c=c[a.C],va(a.J,c)||(a.J=c,Ta(a.g,a.L,a,b,function(){Pa(a.c,a.L,a.C,a.J)}))):a.J&&(a.J=void 0,Ta(a.g,a.L,a,b,function(){Pa(a.c,a.L,a.C,void 0)})):b&&Pa(a.c,a.L,a.C,void 0)},eb=function(a,b,c,d){this.u=a;this.c=b;this.f=c;this.g=d;this.W=void 0;this.v={};this.ua=[];var e=this;this.u.addListener(function(a){db(e,
a)})},fb=function(a){var b=[],c;for(c in a.v){var d=a.v[c].C;d&&b.push(d)}return b},db=function(a,b){if(b.newHash)Da(a.f,fb(a),function(c){for(var d in a.v)cb(a.v[d],b.newHash,c&&c.activeHints)});else for(var c in a.v)cb(a.v[c],b.newHash,void 0)},gb=function(a,b,c,d,e){var g=a.v[b];g||(g=new bb(b,a.c,a.g),a.v[b]=g);a=g;b=c.login_hint;c=c.session_state;a.C!=b?(a.C=b,a.J=b?c:void 0,Ta(a.g,a.L,a,d,e)):e&&e()},hb=function(a,b,c){var d=a.v[b];d?c(!0):Ua(a.g,b,function(e){e?(d=new bb(b,a.c,a.g),a.v[b]=
d,d.C=e.user,d.J=e.session,c(!0)):Ca(a.f,b,function(d){d&&d.valid?(d=new bb(b,a.c,a.g),a.v[b]=d,Ta(a.g,b,d,F(a.u),function(){c(!0)})):c(!1)})})},ib=function(a,b){u()||ka()||la()?a.ua.push(b):ga(ja()?document:window,"storage",b)},S=function(a,b,c){this.b=a;this.c=new Ma(a,b);this.u=new wa(C.ha,C.Va);this.f=new Aa(a,c);this.g=new Sa(a,this.u);this.D=new eb(this.u,this.c,this.f,this.g)};h=S.prototype;
h.start=function(){var a=this,b=function(){a.c.Db.apply(a.c,arguments)},c=function(){R(a.c,{type:"idpReady"});q("Initialize IDP IFrame successfully.")},d=function(c){var d=window;if(d.removeEventListener)d.removeEventListener("message",b,!1);else if(d.detachEvent)d.detachEvent("onmessage",b);else throw"Remove event handler for message failed.";xa(a.u);R(a.c,{type:"idpError",error:c.message})};try{Oa(this.c,this.ia()),ga(window,"message",b),ib(this.D,Qa(this.c)),ib(this.D,Ra(this.c)),za(this.u),k.tb(c,
d)}catch(e){d(e)}};h.zb=function(a){var b=this;hb(this.D,(a.params||{}).clientId,function(c){Q(b.c,a.id,c)})};
h.ib=function(a){var b=a.params||{},c=this,d=function(b){Q(c.c,a.id,b)},e=b.clientId,g=b.loginHint,f=b.request,l=b.sessionSelector;f.client_id=e;f.login_hint=g;f.ss_domain=l.domain;var m=F(this.u);if(m){var v=function(a){a&&!a.error&&a.login_hint?(a.first_issued_at=(new Date).getTime(),a.expires_at=a.first_issued_at+1E3*a.expires_in,a.session_state||(a.session_state={}),a.scope||(a.scope=f.scope),b.skipCache?gb(c.D,e,a,m,function(){d(a)}):Wa(c.g,m,e,f.response_type,a,b.id,function(){gb(c.D,e,a,m,
function(){d(a)})})):(a=a||{},d(a))};b.forceRefresh?Ea(this.f,f,v):Va(this.g,g,e,f.response_type,f.scope,b.id,function(a){a&&18E4<a.expires_at-(new Date).getTime()?gb(c.D,e,a,m,function(){d(a)}):Ea(c.f,f,v)})}else Q(c.c,a.id,{error:"user_logged_out"})};h.nb=function(a){var b=this,c=function(c){Q(b.c,a.id,c)};if(F(this.u)){var d=a.params||{},e=d.request,g=d.sessionSelector;e.client_id=d.clientId;e.login_hint=d.loginHint;e.ss_domain=g.domain;Fa(this.f,e,c)}else c({error:"user_logged_out"})};
h.Fb=function(a){var b=a.params||{},c=b.clientId,d=this;Ha(this.f,b.token,function(b){Xa(d.g,c,function(){Q(d.c,a.id,b)})})};h.Ob=function(a){if(u()||ka()||la()){var b=a.params||{},c=(new M).h({a:b.clientId,id:b.id,origin:b.origin}),b=this.D;if(u()||ka()||la()){b.W&&b.W.stop();b.W=new D(c);for(c=0;c<b.ua.length;c++)b.W.addListener(b.ua[c]);b.W.start()}}Q(this.c,a.id,!0)};h.hb=function(a){var b=this,c=a.params||{};Ya(this.g,c.domain,c.crossSubDomains,c.id,c.policy,function(c){Q(b.c,a.id,c)})};
h.Mb=function(a){var b=a.params||{},c=b.hint,d=!!b.disabled,e=b.domain,g=b.crossSubDomains,f=b.id,l=b.policy,m=this,v;if(c||d)v={hint:c,disabled:d};Za(this.g,e,g,v,f,l,function(){R(m.c,{type:"sessionSelectorChanged",newValue:v,domain:e,crossSubDomains:g,id:f,policy:l});Q(m.c,a.id,!0)})};
h.vb=function(a){var b=a.params||{},c=this,d=function(b){Q(c.c,a.id,b)},e=b.clientId,g=b.request,f=b.sessionSelector;g.client_id=e;g.response_type="id_token";g.ss_domain=f.domain;var l=F(this.u);if(l){var m=function(a){a&&!a.error?(a.first_issued_at=(new Date).getTime(),a.expires_at=a.first_issued_at+1E3*a.expires_in,a.scope=g.scope,ab(c.g,l,e,a,function(){d(a)})):(a=a||{error:"No response returned from Server."},d(a))};b.forceRefresh?Ga(this.f,g,m):$a(this.g,e,g.scope,function(a){a?d(a):Ga(c.f,g,
m)})}else d({scope:g.scope,sessions:[]})};h.Ab=function(a){a=a&&a.params||{};return a.clientId&&!E(a.clientId)};h.sb=function(a){var b=a&&a.params||{};a=b.loginHint;var c=!E(b.id),d=b.clientId&&!E(b.clientId),e=!!b.request,g=e&&b.request.scope;(b=(e=e&&b.request.response_type)&&0<=b.request.response_type.indexOf("code"))&&q("Bad request: 'code' response_type is not supported.");return a&&c&&d&&g&&e&&!b};
h.ob=function(a){a=a&&a.params||{};var b=!E(a.id),c=a.clientId&&!E(a.clientId),d=!!a.request&&a.request.scope;return a.loginHint&&b&&c&&d};h.qb=function(a){a=a&&a.params||{};var b=a.domain&&!E(a.domain),c=!E(a.policy);return!E(a.id)&&b&&c&&this.g.w(a.domain,!!a.crossSubDomains,a.policy)};h.Nb=function(a){a=a&&a.params||{};var b=a.domain&&!E(a.domain),c=!E(a.policy);return!E(a.id)&&b&&c&&this.g.w(a.domain,!!a.crossSubDomains,a.policy)&&C.$a(a)};
h.wb=function(a){a=a&&a.params||{};var b=a.clientId&&!E(a.clientId),c=!!a.request&&a.request.scope;return!E(a.id)&&b&&c};h.Ib=function(a){a=a&&a.params||{};var b=!!a.token,c=a.clientId&&!E(a.clientId);return!E(a.id)&&b&&c};h.Pb=function(a){a=a&&a.params||{};var b=a.origin&&!E(a.origin),c=a.id&&!E(a.id);return a.clientId&&!E(a.clientId)&&b&&c};h.Kb=function(a){var b;if(b=a.clientId)a=a.clientId,b=!(!a||!this.D.v[a]);return b};
h.ab=function(a){var b;if(b=a.clientId)b=a.clientId,b=!(!b||!this.D.v[b]);return b&&a.id&&a.authResult};h.Jb=function(a){return a.domain&&this.g.w(a.domain,a.crossSubDomains,a.policy)};var T=function(a,b){return function(){return b.apply(a,arguments)}};S.prototype.ia=function(){var a={rpcs:[],events:[]};jb(this,a);return a};
var jb=function(a,b){b.rpcs.push({method:"monitorClient",handler:T(a,a.zb),rpcIdRequired:!1,validator:T(a,a.Ab)});b.rpcs.push({method:"getTokenResponse",handler:T(a,a.ib),rpcIdRequired:!0,validator:T(a,a.sb)});b.rpcs.push({method:"getOnlineCode",handler:T(a,a.nb),rpcIdRequired:!0,validator:T(a,a.ob)});b.rpcs.push({method:"getSessionSelector",handler:T(a,a.hb),rpcIdRequired:!0,validator:T(a,a.qb)});b.rpcs.push({method:"setSessionSelector",handler:T(a,a.Mb),rpcIdRequired:!1,validator:T(a,a.Nb)});b.rpcs.push({method:"listIdpSessions",
handler:T(a,a.vb),rpcIdRequired:!0,validator:T(a,a.wb)});b.rpcs.push({method:"revoke",handler:T(a,a.Fb),validator:T(a,a.Ib)});b.rpcs.push({method:"startPolling",handler:T(a,a.Ob),validator:T(a,a.Pb)});b.events.push({type:"idpReady"});b.events.push({type:"idpError"});b.events.push({type:"sessionStateChanged",filter:T(a,a.Kb)});b.events.push({type:"sessionSelectorChanged",filter:T(a,a.Jb)});b.events.push({type:"authResult",filter:T(a,a.ab)})};var kb=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,kb);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};ba(kb,Error);var lb=function(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")};var mb=function(a,b){b.unshift(a);kb.call(this,lb.apply(null,b));b.shift()};ba(mb,kb);var nb=function(a,b,c){if(!a){var d="Assertion failed";if(b)var d=d+(": "+b),e=Array.prototype.slice.call(arguments,2);throw new mb(""+d,e||[]);}};var ob=function(a){for(var b=[],c=0,d=0;d<a.length;d++){for(var e=a.charCodeAt(d);255<e;)b[c++]=e&255,e>>=8;b[c++]=e}return b};var pb=null;var qb=function(){this.s=-1};var U=function(a,b,c){this.s=-1;this.A=a;this.s=c||a.s||16;this.Oa=Array(this.s);this.sa=Array(this.s);a=b;a.length>this.s&&(this.A.update(a),a=this.A.digest(),this.A.reset());for(c=0;c<this.s;c++)b=c<a.length?a[c]:0,this.Oa[c]=b^92,this.sa[c]=b^54;this.A.update(this.sa)};ba(U,qb);U.prototype.reset=function(){this.A.reset();this.A.update(this.sa)};U.prototype.update=function(a,b){this.A.update(a,b)};
U.prototype.digest=function(){var a=this.A.digest();this.A.reset();this.A.update(this.Oa);this.A.update(a);return this.A.digest()};var rb=function(){this.s=64;this.m=Array(4);this.bb=Array(this.s);this.da=this.U=0;this.reset()};ba(rb,qb);rb.prototype.reset=function(){this.m[0]=1732584193;this.m[1]=4023233417;this.m[2]=2562383102;this.m[3]=271733878;this.da=this.U=0};
var sb=function(a,b,c){c||(c=0);var d=Array(16);if("string"==typeof b)for(var e=0;16>e;++e)d[e]=b.charCodeAt(c++)|b.charCodeAt(c++)<<8|b.charCodeAt(c++)<<16|b.charCodeAt(c++)<<24;else for(e=0;16>e;++e)d[e]=b[c++]|b[c++]<<8|b[c++]<<16|b[c++]<<24;b=a.m[0];c=a.m[1];var e=a.m[2],g=a.m[3],f;f=b+(g^c&(e^g))+d[0]+3614090360&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[1]+3905402710&4294967295;g=b+(f<<12&4294967295|f>>>20);f=e+(c^g&(b^c))+d[2]+606105819&4294967295;e=g+(f<<17&4294967295|f>>>15);
f=c+(b^e&(g^b))+d[3]+3250441966&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(g^c&(e^g))+d[4]+4118548399&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[5]+1200080426&4294967295;g=b+(f<<12&4294967295|f>>>20);f=e+(c^g&(b^c))+d[6]+2821735955&4294967295;e=g+(f<<17&4294967295|f>>>15);f=c+(b^e&(g^b))+d[7]+4249261313&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(g^c&(e^g))+d[8]+1770035416&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[9]+2336552879&4294967295;g=b+(f<<12&4294967295|
f>>>20);f=e+(c^g&(b^c))+d[10]+4294925233&4294967295;e=g+(f<<17&4294967295|f>>>15);f=c+(b^e&(g^b))+d[11]+2304563134&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(g^c&(e^g))+d[12]+1804603682&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[13]+4254626195&4294967295;g=b+(f<<12&4294967295|f>>>20);f=e+(c^g&(b^c))+d[14]+2792965006&4294967295;e=g+(f<<17&4294967295|f>>>15);f=c+(b^e&(g^b))+d[15]+1236535329&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(e^g&(c^e))+d[1]+4129170786&4294967295;b=c+(f<<
5&4294967295|f>>>27);f=g+(c^e&(b^c))+d[6]+3225465664&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[11]+643717713&4294967295;e=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(e^g))+d[0]+3921069994&4294967295;c=e+(f<<20&4294967295|f>>>12);f=b+(e^g&(c^e))+d[5]+3593408605&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^e&(b^c))+d[10]+38016083&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[15]+3634488961&4294967295;e=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(e^g))+d[4]+3889429448&4294967295;c=
e+(f<<20&4294967295|f>>>12);f=b+(e^g&(c^e))+d[9]+568446438&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^e&(b^c))+d[14]+3275163606&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[3]+4107603335&4294967295;e=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(e^g))+d[8]+1163531501&4294967295;c=e+(f<<20&4294967295|f>>>12);f=b+(e^g&(c^e))+d[13]+2850285829&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^e&(b^c))+d[2]+4243563512&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[7]+1735328473&4294967295;
e=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(e^g))+d[12]+2368359562&4294967295;c=e+(f<<20&4294967295|f>>>12);f=b+(c^e^g)+d[5]+4294588738&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[8]+2272392833&4294967295;g=b+(f<<11&4294967295|f>>>21);f=e+(g^b^c)+d[11]+1839030562&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[14]+4259657740&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(c^e^g)+d[1]+2763975236&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[4]+1272893353&4294967295;g=b+(f<<11&4294967295|
f>>>21);f=e+(g^b^c)+d[7]+4139469664&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[10]+3200236656&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(c^e^g)+d[13]+681279174&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[0]+3936430074&4294967295;g=b+(f<<11&4294967295|f>>>21);f=e+(g^b^c)+d[3]+3572445317&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[6]+76029189&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(c^e^g)+d[9]+3654602809&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[12]+
3873151461&4294967295;g=b+(f<<11&4294967295|f>>>21);f=e+(g^b^c)+d[15]+530742520&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[2]+3299628645&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(e^(c|~g))+d[0]+4096336452&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[7]+1126891415&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[14]+2878612391&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[5]+4237533241&4294967295;c=e+(f<<21&4294967295|f>>>11);f=b+(e^(c|~g))+d[12]+1700485571&
4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[3]+2399980690&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[10]+4293915773&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[1]+2240044497&4294967295;c=e+(f<<21&4294967295|f>>>11);f=b+(e^(c|~g))+d[8]+1873313359&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[15]+4264355552&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[6]+2734768916&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[13]+1309151649&
4294967295;c=e+(f<<21&4294967295|f>>>11);f=b+(e^(c|~g))+d[4]+4149444226&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[11]+3174756917&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[2]+718787259&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[9]+3951481745&4294967295;a.m[0]=a.m[0]+b&4294967295;a.m[1]=a.m[1]+(e+(f<<21&4294967295|f>>>11))&4294967295;a.m[2]=a.m[2]+e&4294967295;a.m[3]=a.m[3]+g&4294967295};
rb.prototype.update=function(a,b){void 0===b&&(b=a.length);for(var c=b-this.s,d=this.bb,e=this.U,g=0;g<b;){if(0==e)for(;g<=c;)sb(this,a,g),g+=this.s;if("string"==typeof a)for(;g<b;){if(d[e++]=a.charCodeAt(g++),e==this.s){sb(this,d);e=0;break}}else for(;g<b;)if(d[e++]=a[g++],e==this.s){sb(this,d);e=0;break}}this.U=e;this.da+=b};
rb.prototype.digest=function(){var a=Array((56>this.U?this.s:2*this.s)-this.U);a[0]=128;for(var b=1;b<a.length-8;++b)a[b]=0;for(var c=8*this.da,b=a.length-8;b<a.length;++b)a[b]=c&255,c/=256;this.update(a);a=Array(16);for(b=c=0;4>b;++b)for(var d=0;32>d;d+=8)a[c++]=this.m[b]>>>d&255;return a};var tb=function(a,b){for(var c=0;c<a.length;c++)for(var d=0;d<b.length;d++)if(a[c]&&b[d]&&a[c].toLowerCase()===b[d].toLowerCase())return!0;return!1};var vb=function(a,b,c){b.origin=a.b;b.privileged=!0;b.redirect_uri=void 0;b.response_type=void 0;G(C.ga,b,ub(a),c,!1)},wb=function(a,b,c,d){G((window.NOW_SERVER_BASE_URL||"https://clients1.google.com")+"/nowapi/webauth",{origin:a.b,client_id:b,user_ids:c.join(";")},ub(a),d,!0)},xb=function(a,b,c){G("/o/oauth2/auth",{origin:a.b,client_id:b.client_id,login_hint:b.login_hint,response_type:"code",access_type:"offline",scope:"https://www.googleapis.com/auth/googlenow.publish",redirect_uri:"xhr",timestamp:b.timestamp,
signature:b.signature,signed_by:"google_now"},ub(a),c,!1)},V=function(a,b,c){G((window.NOW_SERVER_BASE_URL||"https://clients1.google.com")+"/nowapi/webAuthApiAnalytics",{origin:a.b,client_id:b,status:c},ub(a),function(){},!0)},ub=function(a){var b={},c=n.H(C.pb());if(c){a=a.b;if(!a||!c)throw Error("RP origin and session cookie value cannot be empty.");c=new U(new rb,ob(c));a=ob(a);c.reset();c.update(a);c=c.digest();a=aa(c);nb("array"==a||"object"==a&&"number"==typeof c.length,"encodeByteArray takes an array as a parameter");
if(!pb)for(pb={},a=0;65>a;a++)pb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a);a=pb;for(var d=[],e=0;e<c.length;e+=3){var g=c[e],f=e+1<c.length,l=f?c[e+1]:0,m=e+2<c.length,v=m?c[e+2]:0,Bb=g>>2,g=(g&3)<<4|l>>4,l=(l&15)<<2|v>>6,v=v&63;m||(v=64,f||(l=64));d.push(a[Bb],a[g],a[l],a[v])}b["X-Csrf-Token"]=d.join("")}return b};var W=function(){};t(W,L);W.prototype.h=function(a){return["now_as",a.R,a.a||"ALL_CLIENTS"].join(C.i)};W.prototype.G=function(a){var b={};if(a){a=a.split(C.i);if("now_as"!==a[0]||3!=a.length)throw Error("Invalid assertion cache key.");b.R=a[1];b.a="ALL_CLIENTS"==a[2]?void 0:a[2]}return b};W.prototype.l=function(a,b,c){var d=this;L.prototype.l.call(this,a,b,function(b){b&&b.e?b.e<(new Date).getTime()?J(d).removeItem(d.h(a),c):c&&c(b.o):c&&c(void 0)})};
W.prototype.j=function(a,b,c,d){if(void 0!==b){var e=!!b;if(e&&!a.a)throw Error("Cannot cache all clients enabled for a user.");b={};b.o=e;b.e=(new Date).getTime()+864E5}L.prototype.j.call(this,a,b,c,d)};var yb=function(a,b,c,d){var e={R:b,a:c};a.l({R:b},void 0,function(b){!1===b?d(!1):a.l(e,void 0,d)})},zb=function(a,b,c,d){a.j({R:b},void 0,void 0,function(){a.j({R:b,a:c},!0,void 0,d)})},Ab=function(a,b,c,d,e){a.j({R:b,a:d?void 0:c},!1,void 0,e)};var Cb=function(){};t(Cb,K);Cb.prototype.h=function(a){return["now_gs",a.origin,a.a].join(C.i)};Cb.prototype.l=function(a,b,c){var d=this;K.prototype.l.call(this,a,b,function(b){var e;b&&b.expires_at&&(b.expires_at<=(new Date).getTime()?J(d).removeItem(d.h(a),function(){c&&c(e)}):(b.expires_at=void 0,e=b));c&&c(e)})};Cb.prototype.j=function(a,b,c,d){b&&(b.expires_at=(new Date).getTime()+864E5);K.prototype.j.call(this,a,b,c,d)};S.prototype.jb=function(a){var b=this;if(!Db(this,"getCode",a.id)){var c=Eb(this,a);if(3<c.ka.length)X(c,"THROTTLED","At most 3 email addresses can be used."),V(this.f,c.a,1);else if(c.Z){var d=function(a){a.length?Fb(b,c,a,function(a){Gb(b,c,a.auth_request)}):(X(c,"DISABLED"),V(b.f,c.a,4))},e=function(a){"AUTH_EXISTS"==a.message&&(X(c,"AUTHORIZATION_EXISTS","Authorization already granted for the user."),V(b.f,c.a,3))};Hb(this,c,!1,function(a){Ib(b,c,a,void 0,d,e)})}else X(c,"DISABLED"),V(this.f,
c.a,2)}};S.prototype.Gb=function(a){var b=this;if(!Db(this,"revokeNow",a.id)){var c=Eb(this,a);3<c.ka.length&&X(c,"THROTTLED","At most 3 email addresses can be used.");if(c.Z){var d=function(a){if(a.length)for(var d=a.length,e=0;e<a.length;e++)Jb(b,c.a,a[e],function(a){(a=a&&a.access_token)?Ha(b.f,a,function(){d--;d||c.O({})}):(d--,d||c.O({}))});else c.O({})},e=function(){};Hb(this,c,!0,function(a){Ib(b,c,a,!0,d,e)})}else c.O({})}};
var Db=function(a,b,c){a.qa=a.qa||{};if(!a.qa[b])return a.qa[b]=!0,!1;Q(a.c,c,{error:"THROTTLED",detail:"The "+b+"() method has already been invoked."});return!0},Eb=function(a,b){var c=b.params||{},d={a:c.clientId,ka:c.emails,O:function(c){Q(a.c,b.id,c)}};d.Z=F(a.u);d.Sa={origin:a.b,a:c.clientId};return d},Hb=function(a,b,c,d){a.M||(a.M=new Cb);var e=function(c){c&&c.sessions?a.M.j(b.Sa,c,b.Z,function(){d(c)}):X(b,"OTHER","Failed to get Google session information.")},g={client_id:b.a,scope:"https://www.googleapis.com/auth/googlenow.publish"};
c?vb(a.f,g,e):a.M.l(b.Sa,b.Z,function(b){b?d(b):vb(a.f,g,e)})},Ib=function(a,b,c,d,e,g){a.K||(a.K=new W);var f=function(a){e&&e(a)},l=function(){var a=Error("AUTH_EXISTS");g&&g(a)};if(c.sessions&&c.sessions.length){var m=function(c,e){if(0==c.length)f(e);else{var g=c.shift();g.emails&&tb(b.ka,g.emails)?d&&g.login_hint?(e.push(g.login_hint),m(c,e)):d?m(c,e):g.login_hint?l():g.obfuscatedGaiaId?yb(a.K,g.obfuscatedGaiaId,b.a,function(a){a?l():(void 0===a&&e.push(g.obfuscatedGaiaId),m(c,e))}):m(c,e):m(c,
e)}};m(c.sessions.slice(0),[])}else f([])},Fb=function(a,b,c,d){a.K||(a.K=new W);wb(a.f,b.a,c,function(e){if(e&&"DISABLED"!=e.status)"THROTTLED"==e.status?(X(b,"THROTTLED","Throttled by Google Now server."),V(a.f,b.a,7)):"OK"==e.status&&Kb(a,b,e,c)?zb(a.K,e.auth_request.login_hint,b.a,function(){d(e)}):(X(b,"OTHER","Unexpected response from Google Now server."),V(a.f,b.a,8));else{var g=!1,f=!1;if(e.users&&e.users.length){var l=function(c,d){if(0==c.length)d();else{var e=c.shift();e.user_id?Ab(a.K,
e.user_id,b.a,e.disabled_for_all_clients,function(){e.disabled_for_all_clients?f=!0:g=!0;l(c,d)}):l(c,d)}};l(e.users.slice(0),function(){X(b,"DISABLED");V(a.f,b.a,f&&!g?5:6)})}else X(b,"DISABLED"),V(a.f,b.a,f&&!g?5:6)}})},Kb=function(a,b,c,d){c=c.auth_request;return!!c&&c.origin==a.b&&c.client_id==b.a&&0<c.timestamp&&!!c.signature&&"google_now"==c.signed_by&&0<=r(d,c.login_hint)},Gb=function(a,b,c){xb(a.f,c,function(c){c&&c.code?(b.O({code:c.code}),V(a.f,b.a,9)):c&&"immediate_failed"==c.error&&"policy_enforced"==
c.error_subtype?(X(b,"AUTHORIZATION_EXISTS","Failed to issue code due to existing authorization."),V(a.f,b.a,10)):(X(b,"OTHER",c.error||"Failed to get code."),V(a.f,b.a,11))})},Jb=function(a,b,c,d){Ea(a.f,{client_id:b,login_hint:c,response_type:"token",scope:"https://www.googleapis.com/auth/googlenow.publish"},d)},X=function(a,b,c){a.O({error:b,detail:c})};S.prototype.kb=function(a){a=a&&a.params||{};var b=a.emails,b=b&&b.length&&"[object Array]"===Object.prototype.toString.call(b);return a.clientId&&!E(a.clientId)&&b};S.prototype.Hb=function(a){a=a&&a.params||{};var b=a.emails,b=b&&b.length&&"[object Array]"===Object.prototype.toString.call(b);return a.clientId&&!E(a.clientId)&&b};S.prototype.ia=function(){var a={rpcs:[],events:[]};Lb(this,a);return a};
var Lb=function(a,b){b.rpcs.push({method:"now:getCode",handler:T(a,a.jb),rpcIdRequired:!0,validator:T(a,a.kb)});b.rpcs.push({method:"now:revoke",handler:T(a,a.Gb),rpcIdRequired:!0,validator:T(a,a.Hb)})};S.prototype.ia=function(){var a={rpcs:[],events:[]};jb(this,a);Lb(this,a);return a};C.ha="APISID";C.Fa="SAPISID";C.Ha="/o/oauth2/iframerpc?action=sessionState";C.za="/o/oauth2/iframerpc?action=checkOrigin";C.Ea="/o/oauth2/iframerpc?action=issueToken";C.Da="/o/oauth2/iframerpc?action=issueOnlineCode";C.ga="/o/oauth2/iframerpc?action=listSessions";
var Mb=function(){var a=fa("origin");if(!a)throw"Failed to get parent origin from URL hash!";var b=fa("rpcToken");if(!b)throw"Failed to get rpcToken from URL hash!";var c=fa("debug");ca="0"!=c&&!!c;(new S(a,b)).start()},Nb=["lso","startIdpIFrame"],Y=this;Nb[0]in Y||!Y.execScript||Y.execScript("var "+Nb[0]);for(var Z;Nb.length&&(Z=Nb.shift());)Nb.length||void 0===Mb?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=Mb;
