# Global River Obstructions Database (GROD) Project

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;River obstructions in the form of dams, locks, and other such barriers, are a globally important impact that humans have had on the movement of water, sediment, organisms, and nutrients from ocean to sea. Despite existing datasets of the worlds largest dams like GRanD, there is not a global inventory of obstructions to rivers. That is the goal of this project: Identify and categorize human-built river barriers for rivers wider than 30 meters across the globe. These barriers can vary enormously in their size, volume of water disrupted, and biological permeability (can fish swim past them?). We will try to capture some of this broad variation in river obstructions, so we need to be clear about the different barriers that may cross a river, which are listed here in order from most impermeable to most permeable.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;We will be using Google Earth Engine and the Global River Widths from Landsat dataset generated by George Allen and Tamlin Pavelsky. Instructions and code can be found at the links below. 

## Links
### Validation instructions and code
**Validation tutorial:** <https://globalhydrologylab.github.io/GROD/validation>

**Validation code:** <https://github.com/GlobalHydrologyLab/GROD/blob/master/1_user_interface_script/GROD_validation.js>

### Full tutorial and code
**Instructional tutorial:** <https://globalhydrologylab.github.io/GROD/>

**Code:** <https://github.com/GlobalHydrologyLab/GROD/blob/master/1_user_interface_script/GROD.js>

